package service

import (
	"context"
	"log"
	"math"

	analyticspb "gymtracker-backend/proto/analytics"
)

// AnalyticsServer implements the gRPC AnalyticsServiceServer interface generated by protoc
type AnalyticsServer struct {
	analyticspb.UnimplementedAnalyticsServiceServer
}

// NewAnalyticsServer creates a new instance of AnalyticsServer
func NewAnalyticsServer() *AnalyticsServer {
	return &AnalyticsServer{}
}

// roundToTwoDecimals rounds a float64 to two decimal places
func roundToTwoDecimals(val float64) float64 {
	return math.Round(val*100) / 100
}

// Calculate1RM performs multi-formula 1-Rep Max estimations and training zone calculations
func (s *AnalyticsServer) Calculate1RM(ctx context.Context, req *analyticspb.OneRMRequest) (*analyticspb.OneRMResponse, error) {
	log.Printf("📊 [gRPC Analytics] Calculate1RM called with weight=%.2f kg, reps=%d", req.GetWeightKg(), req.GetReps())
	weight := req.GetWeightKg()
	reps := float64(req.GetReps())

	if reps <= 0 || weight <= 0 {
		return &analyticspb.OneRMResponse{
			Epley_1Rm:    roundToTwoDecimals(weight),
			Brzycki_1Rm:  roundToTwoDecimals(weight),
			Lombardi_1Rm: roundToTwoDecimals(weight),
			Average_1Rm:  roundToTwoDecimals(weight),
			TrainingZones: &analyticspb.TrainingZones{
				HeavyStrength_90: roundToTwoDecimals(weight * 0.90),
				Hypertrophy_75:   roundToTwoDecimals(weight * 0.75),
				Endurance_60:     roundToTwoDecimals(weight * 0.60),
			},
		}, nil
	}

	// 1. Epley Formula: 1RM = Weight * (1 + Reps/30)
	epley := weight * (1.0 + reps/30.0)

	// 2. Brzycki Formula: 1RM = Weight * (36 / (37 - Reps)) (capped for reps < 37)
	brzycki := epley
	if reps < 37 {
		brzycki = weight * (36.0 / (37.0 - reps))
	}

	// 3. Lombardi Formula: 1RM = Weight * Reps^0.10
	lombardi := weight * math.Pow(reps, 0.10)

	// 4. Average 1RM estimation across all formulas
	average := (epley + brzycki + lombardi) / 3.0

	return &analyticspb.OneRMResponse{
		Epley_1Rm:    roundToTwoDecimals(epley),
		Brzycki_1Rm:  roundToTwoDecimals(brzycki),
		Lombardi_1Rm: roundToTwoDecimals(lombardi),
		Average_1Rm:  roundToTwoDecimals(average),
		TrainingZones: &analyticspb.TrainingZones{
			HeavyStrength_90: roundToTwoDecimals(average * 0.90),
			Hypertrophy_75:   roundToTwoDecimals(average * 0.75),
			Endurance_60:     roundToTwoDecimals(average * 0.60),
		},
	}, nil
}

// CalculateVolumeLoad calculates total tonnage, total reps, and average intensity across workout sets
func (s *AnalyticsServer) CalculateVolumeLoad(ctx context.Context, req *analyticspb.VolumeRequest) (*analyticspb.VolumeResponse, error) {
	var totalVolume float64
	var totalReps int32

	for _, set := range req.GetSets() {
		totalVolume += set.GetWeightKg() * float64(set.GetReps())
		totalReps += set.GetReps()
	}

	var avgIntensity float64
	if totalReps > 0 {
		avgIntensity = totalVolume / float64(totalReps)
	}

	return &analyticspb.VolumeResponse{
		TotalVolumeKg:      roundToTwoDecimals(totalVolume),
		TotalReps:          totalReps,
		AverageIntensityKg: roundToTwoDecimals(avgIntensity),
	}, nil
}
