// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/analytics/analytics.proto

package analyticspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to calculate 1RM
type OneRMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float64                `protobuf:"fixed64,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Reps          int32                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneRMRequest) Reset() {
	*x = OneRMRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneRMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneRMRequest) ProtoMessage() {}

func (x *OneRMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneRMRequest.ProtoReflect.Descriptor instead.
func (*OneRMRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *OneRMRequest) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *OneRMRequest) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

// Training weight recommendations based on percentage of 1RM
type TrainingZones struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HeavyStrength_90 float64                `protobuf:"fixed64,1,opt,name=heavy_strength_90,json=heavyStrength90,proto3" json:"heavy_strength_90,omitempty"` // 90% of 1RM (1-3 reps strength)
	Hypertrophy_75   float64                `protobuf:"fixed64,2,opt,name=hypertrophy_75,json=hypertrophy75,proto3" json:"hypertrophy_75,omitempty"`         // 75% of 1RM (8-12 reps muscle growth)
	Endurance_60     float64                `protobuf:"fixed64,3,opt,name=endurance_60,json=endurance60,proto3" json:"endurance_60,omitempty"`               // 60% of 1RM (15+ reps endurance)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrainingZones) Reset() {
	*x = TrainingZones{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainingZones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainingZones) ProtoMessage() {}

func (x *TrainingZones) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainingZones.ProtoReflect.Descriptor instead.
func (*TrainingZones) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TrainingZones) GetHeavyStrength_90() float64 {
	if x != nil {
		return x.HeavyStrength_90
	}
	return 0
}

func (x *TrainingZones) GetHypertrophy_75() float64 {
	if x != nil {
		return x.Hypertrophy_75
	}
	return 0
}

func (x *TrainingZones) GetEndurance_60() float64 {
	if x != nil {
		return x.Endurance_60
	}
	return 0
}

// Response containing multiple 1RM formulas and training zones
type OneRMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epley_1Rm     float64                `protobuf:"fixed64,1,opt,name=epley_1rm,json=epley1rm,proto3" json:"epley_1rm,omitempty"`
	Brzycki_1Rm   float64                `protobuf:"fixed64,2,opt,name=brzycki_1rm,json=brzycki1rm,proto3" json:"brzycki_1rm,omitempty"`
	Lombardi_1Rm  float64                `protobuf:"fixed64,3,opt,name=lombardi_1rm,json=lombardi1rm,proto3" json:"lombardi_1rm,omitempty"`
	Average_1Rm   float64                `protobuf:"fixed64,4,opt,name=average_1rm,json=average1rm,proto3" json:"average_1rm,omitempty"`
	TrainingZones *TrainingZones         `protobuf:"bytes,5,opt,name=training_zones,json=trainingZones,proto3" json:"training_zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneRMResponse) Reset() {
	*x = OneRMResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneRMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneRMResponse) ProtoMessage() {}

func (x *OneRMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneRMResponse.ProtoReflect.Descriptor instead.
func (*OneRMResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *OneRMResponse) GetEpley_1Rm() float64 {
	if x != nil {
		return x.Epley_1Rm
	}
	return 0
}

func (x *OneRMResponse) GetBrzycki_1Rm() float64 {
	if x != nil {
		return x.Brzycki_1Rm
	}
	return 0
}

func (x *OneRMResponse) GetLombardi_1Rm() float64 {
	if x != nil {
		return x.Lombardi_1Rm
	}
	return 0
}

func (x *OneRMResponse) GetAverage_1Rm() float64 {
	if x != nil {
		return x.Average_1Rm
	}
	return 0
}

func (x *OneRMResponse) GetTrainingZones() *TrainingZones {
	if x != nil {
		return x.TrainingZones
	}
	return nil
}

// Single set data for volume calculation
type SetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightKg      float64                `protobuf:"fixed64,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Reps          int32                  `protobuf:"varint,2,opt,name=reps,proto3" json:"reps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetData) Reset() {
	*x = SetData{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetData) ProtoMessage() {}

func (x *SetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetData.ProtoReflect.Descriptor instead.
func (*SetData) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *SetData) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *SetData) GetReps() int32 {
	if x != nil {
		return x.Reps
	}
	return 0
}

// Request to calculate volume load for multiple sets
type VolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sets          []*SetData             `protobuf:"bytes,1,rep,name=sets,proto3" json:"sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeRequest) Reset() {
	*x = VolumeRequest{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRequest) ProtoMessage() {}

func (x *VolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRequest.ProtoReflect.Descriptor instead.
func (*VolumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeRequest) GetSets() []*SetData {
	if x != nil {
		return x.Sets
	}
	return nil
}

// Response with volume metrics
type VolumeResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalVolumeKg      float64                `protobuf:"fixed64,1,opt,name=total_volume_kg,json=totalVolumeKg,proto3" json:"total_volume_kg,omitempty"`
	TotalReps          int32                  `protobuf:"varint,2,opt,name=total_reps,json=totalReps,proto3" json:"total_reps,omitempty"`
	AverageIntensityKg float64                `protobuf:"fixed64,3,opt,name=average_intensity_kg,json=averageIntensityKg,proto3" json:"average_intensity_kg,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VolumeResponse) Reset() {
	*x = VolumeResponse{}
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeResponse) ProtoMessage() {}

func (x *VolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeResponse.ProtoReflect.Descriptor instead.
func (*VolumeResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeResponse) GetTotalVolumeKg() float64 {
	if x != nil {
		return x.TotalVolumeKg
	}
	return 0
}

func (x *VolumeResponse) GetTotalReps() int32 {
	if x != nil {
		return x.TotalReps
	}
	return 0
}

func (x *VolumeResponse) GetAverageIntensityKg() float64 {
	if x != nil {
		return x.AverageIntensityKg
	}
	return 0
}

var File_proto_analytics_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/analytics/analytics.proto\x12\tanalytics\"?\n" +
	"\fOneRMRequest\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x01R\bweightKg\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x05R\x04reps\"\x85\x01\n" +
	"\rTrainingZones\x12*\n" +
	"\x11heavy_strength_90\x18\x01 \x01(\x01R\x0fheavyStrength90\x12%\n" +
	"\x0ehypertrophy_75\x18\x02 \x01(\x01R\rhypertrophy75\x12!\n" +
	"\fendurance_60\x18\x03 \x01(\x01R\vendurance60\"\xd2\x01\n" +
	"\rOneRMResponse\x12\x1b\n" +
	"\tepley_1rm\x18\x01 \x01(\x01R\bepley1rm\x12\x1f\n" +
	"\vbrzycki_1rm\x18\x02 \x01(\x01R\n" +
	"brzycki1rm\x12!\n" +
	"\flombardi_1rm\x18\x03 \x01(\x01R\vlombardi1rm\x12\x1f\n" +
	"\vaverage_1rm\x18\x04 \x01(\x01R\n" +
	"average1rm\x12?\n" +
	"\x0etraining_zones\x18\x05 \x01(\v2\x18.analytics.TrainingZonesR\rtrainingZones\":\n" +
	"\aSetData\x12\x1b\n" +
	"\tweight_kg\x18\x01 \x01(\x01R\bweightKg\x12\x12\n" +
	"\x04reps\x18\x02 \x01(\x05R\x04reps\"7\n" +
	"\rVolumeRequest\x12&\n" +
	"\x04sets\x18\x01 \x03(\v2\x12.analytics.SetDataR\x04sets\"\x89\x01\n" +
	"\x0eVolumeResponse\x12&\n" +
	"\x0ftotal_volume_kg\x18\x01 \x01(\x01R\rtotalVolumeKg\x12\x1d\n" +
	"\n" +
	"total_reps\x18\x02 \x01(\x05R\ttotalReps\x120\n" +
	"\x14average_intensity_kg\x18\x03 \x01(\x01R\x12averageIntensityKg2\xa1\x01\n" +
	"\x10AnalyticsService\x12A\n" +
	"\fCalculate1RM\x12\x17.analytics.OneRMRequest\x1a\x18.analytics.OneRMResponse\x12J\n" +
	"\x13CalculateVolumeLoad\x12\x18.analytics.VolumeRequest\x1a\x19.analytics.VolumeResponseB0Z.gymtracker-backend/proto/analytics;analyticspbb\x06proto3"

var (
	file_proto_analytics_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_analytics_proto_rawDescData []byte
)

func file_proto_analytics_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_analytics_proto_rawDescData
}

var file_proto_analytics_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_analytics_analytics_proto_goTypes = []any{
	(*OneRMRequest)(nil),   // 0: analytics.OneRMRequest
	(*TrainingZones)(nil),  // 1: analytics.TrainingZones
	(*OneRMResponse)(nil),  // 2: analytics.OneRMResponse
	(*SetData)(nil),        // 3: analytics.SetData
	(*VolumeRequest)(nil),  // 4: analytics.VolumeRequest
	(*VolumeResponse)(nil), // 5: analytics.VolumeResponse
}
var file_proto_analytics_analytics_proto_depIdxs = []int32{
	1, // 0: analytics.OneRMResponse.training_zones:type_name -> analytics.TrainingZones
	3, // 1: analytics.VolumeRequest.sets:type_name -> analytics.SetData
	0, // 2: analytics.AnalyticsService.Calculate1RM:input_type -> analytics.OneRMRequest
	4, // 3: analytics.AnalyticsService.CalculateVolumeLoad:input_type -> analytics.VolumeRequest
	2, // 4: analytics.AnalyticsService.Calculate1RM:output_type -> analytics.OneRMResponse
	5, // 5: analytics.AnalyticsService.CalculateVolumeLoad:output_type -> analytics.VolumeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_analytics_analytics_proto_init() }
func file_proto_analytics_analytics_proto_init() {
	if File_proto_analytics_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_analytics_proto_rawDesc), len(file_proto_analytics_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_analytics_proto = out.File
	file_proto_analytics_analytics_proto_goTypes = nil
	file_proto_analytics_analytics_proto_depIdxs = nil
}
